"""Synthesize executor SFT rows with no intent/template in the model input.

Purpose: ablation training for validating whether explicit intent and answer
template fields are useful. The new rows use only:

- user question
- external reference information

as the user-side input. By default the assistant target is regenerated by the
teacher API under the same no-intent/no-template prompt. A legacy ``copy`` mode
is kept for debugging.

The output schema matches ``agent.merge_final_sft`` executor input, so it can be
merged into final prompt JSONL directly:

    python -m agent.build_executor_no_intent_sft \
    --input agent/outputs/health/valid_executor_answer_sft.jsonl \
    --output agent/outputs/health/valid_executor_no_intent_sft.jsonl

    python -m agent.merge_final_sft \
    --planner-final agent/outputs/health/valid_planner_final_prompt.jsonl \
    --executor-input agent/outputs/health/valid_executor_no_intent_sft.jsonl \
    --output agent/outputs/health/valid_no_intent_merged_sft.jsonl
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import re
from pathlib import Path
from typing import Any

from openai import AsyncOpenAI
from tqdm import tqdm

try:
    from .config import DistillConfig, output_file_for_domain, resolve_base_url, resolve_distill_model
except ImportError:  # Allows: python agent/build_executor_no_intent_sft.py
    from config import DistillConfig, output_file_for_domain, resolve_base_url, resolve_distill_model  # type: ignore

DEFAULT_INPUT = output_file_for_domain("executor_answer_sft")
DEFAULT_OUTPUT = output_file_for_domain("executor_no_intent_sft")
DEFAULT_MAX_ATTEMPTS = 3

NO_INTENT_EXECUTOR_SYSTEM_PROMPT = """你是健康管理助手。你是一位经验丰富、温和耐心的健康管理顾问。

当前任务是执行阶段：基于用户问题和外部参考信息，生成面向用户的最终健康管理回复。
你会收到用户问题和外部参考信息。外部参考信息可能来自本地知识库、网络检索结果或其他资料。

【回答要求】
1. 先理解用户核心诉求，并围绕用户问题本身作答。
2. 优先使用外部参考信息；外部信息不足时，可结合通用健康管理常识补充，但保持谨慎。
3. 回答要结构清晰、语言温和、具体可执行，避免机械复述参考资料。
4. 可以结合中医养生理论和现代营养学/运动科学常识，但表述要通俗，贴近生活。
5. 重点回答健康管理相关内容，不要过多涉及临床或医疗领域。超出健康管理范畴的问题，优先给出科学的生活方式建议，避免涉及诊断、用药、治疗等专业医疗内容。
6. 涉及疾病、手术、孕产、儿童、用药、严重症状或检查异常时，加入遵医嘱或及时就医提醒。
7. 给出符合实际的预期，鼓励循序渐进、长期坚持，不夸大效果，不制造焦虑。
8. 若用户问题和外部参考信息有冲突，优先遵循外部参考信息和安全原则。
9. 只输出面向用户的最终回答，不输出规划动作，不调用工具，不输出 JSON，不提及“工具调用”“planning_finish”“下游模块”。"""

TEACHER_SYSTEM_PROMPT = """你是健康管理助手的执行阶段。请根据用户问题和外部参考信息，给出最终面向用户的健康管理回复。

【回答要求】
1. 先理解用户核心诉求，并围绕用户问题本身作答。
2. 优先使用外部参考信息；外部信息不足时，可结合通用健康管理常识补充，但保持谨慎。
3. 回答要结构清晰、语言温和、具体可执行，避免机械复述参考资料。
4. 可以结合中医养生理论和现代营养学/运动科学常识，但表述要通俗，贴近生活。
5. 重点回答健康管理相关内容，不要过多涉及临床或医疗领域。超出健康管理范畴的问题，优先给出科学的生活方式建议，避免涉及诊断、用药、治疗等专业医疗内容。
6. 涉及疾病、手术、孕产、儿童、用药、严重症状或检查异常时，加入遵医嘱或及时就医提醒。
7. 给出符合实际的预期，鼓励循序渐进、长期坚持，不夸大效果，不制造焦虑。
8. 若用户问题和外部参考信息有冲突，优先遵循外部参考信息和安全原则。
9. 只输出面向用户的最终回答，不输出规划动作，不调用工具，不输出 JSON，不提及“工具调用”“planning_finish”“下游模块”。
"""

FORBIDDEN_LEAK_PHRASES = (
    "已识别意图",
    "识别意图",
    "显式意图",
    "意图字段",
    "回答模板",
    "answer_template",
    "规划动作",
    "planning_finish",
    "工具调用",
    "下游模块",
)


_THINK_PATTERN = re.compile(r"<think>(.*?)</think>", flags=re.S)


def split_reasoning_and_answer(
    raw_content: str | None,
    server_reasoning: str | None,
) -> tuple[str, str]:
    """Pull reasoning out of either the OpenAI ``reasoning_content`` field or
    inline ``<think>...</think>`` tags. Returns (reasoning, answer) with answer
    free of stray think tags. Both fields may be empty strings if the model
    didn't emit a thought.
    """

    text = (raw_content or "").strip()
    server_reasoning = (server_reasoning or "").strip()
    if server_reasoning:
        cleaned = _THINK_PATTERN.sub("", text).strip()
        return server_reasoning, cleaned

    matches = list(_THINK_PATTERN.finditer(text))
    if matches:
        reasoning_parts = [m.group(1).strip() for m in matches if m.group(1).strip()]
        reasoning = "\n\n".join(reasoning_parts)
        cleaned = _THINK_PATTERN.sub("", text).strip()
        return reasoning, cleaned

    # tolerate a missing closing </think>
    if "<think>" in text and "</think>" not in text:
        head, _, tail = text.partition("<think>")
        return tail.strip(), head.strip()

    return "", text


def validate_synthesized(parsed: Any) -> tuple[bool, str]:
    if not isinstance(parsed, dict):
        return False, "not_dict"
    reasoning = str(parsed.get("reasoning") or "").strip()
    answer = str(parsed.get("answer") or "").strip()
    if not answer:
        return False, "empty_answer"
    if len(answer) < 80:
        return False, f"answer_too_short={len(answer)}"
    if len(answer) > 2500:
        return False, f"answer_too_long={len(answer)}"
    text = reasoning + "\n" + answer
    if any(phrase in text for phrase in FORBIDDEN_LEAK_PHRASES):
        return False, "leak_hidden_field_phrase"
    return True, ""


async def call_teacher(
    client: AsyncOpenAI,
    model_name: str,
    user_query: str,
    external_info: str,
    max_retries: int,
) -> dict[str, Any] | None:
    external_info = external_info.strip() or "无外部补充信息。"
    user_prompt = build_user_prompt(user_query, external_info)
    for attempt in range(max_retries):
        try:
            completion = await client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": TEACHER_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.75,
                top_p=0.9,
            )
            message = completion.choices[0].message
            raw_content = message.content or ""
            server_reasoning = getattr(message, "reasoning_content", None)
            reasoning, answer = split_reasoning_and_answer(raw_content, server_reasoning)
            return {"reasoning": reasoning, "answer": answer, "raw": raw_content}
        except Exception as exc:
            if attempt < max_retries - 1:
                await asyncio.sleep(min(2**attempt, 20) + 1)
            else:
                print(f"\n[失败] teacher API 达到最大重试次数：{exc}")
                return None
    return None


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(row, dict):
                rows.append(row)
    return rows


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def existing_ids(path: Path) -> set[str]:
    ids: set[str] = set()
    if not path.exists():
        return ids
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            row_id = row.get("id")
            if row_id:
                ids.add(str(row_id))
    return ids


def build_user_prompt(user_query: str, external_info: str) -> str:
    external_info = external_info.strip() or "无外部补充信息。"
    return f"""【用户问题】
{user_query.strip()}

【外部参考信息】
{external_info}
"""


def build_assistant_content(raw: dict[str, Any], include_reasoning: bool = False) -> str | None:
    answer = raw.get("content") if isinstance(raw, dict) else None
    if not isinstance(answer, str) or not answer.strip():
        return None
    reasoning = raw.get("reasoning_content") if include_reasoning and isinstance(raw, dict) else None
    if isinstance(reasoning, str) and reasoning.strip():
        return f"<think>\n{reasoning.strip()}\n</think>\n{answer.strip()}"
    return answer.strip()


def build_output_row(
    row: dict[str, Any],
    answer: str,
    reasoning: str | None,
    include_reasoning: bool,
    source_tag: str,
) -> dict[str, Any] | None:
    user_query = str(row.get("user_query") or "").strip()
    if not user_query:
        return None
    external_info = str(row.get("external_info") or "")
    answer = (answer or "").strip()
    reasoning = (reasoning or "").strip() if reasoning else None
    if not answer:
        return None
    assistant_content = f"<think>\n{reasoning}\n</think>\n{answer}" if include_reasoning and reasoning else answer

    messages = [
        {"role": "system", "content": NO_INTENT_EXECUTOR_SYSTEM_PROMPT},
        {"role": "user", "content": build_user_prompt(user_query, external_info)},
        {"role": "assistant", "content": assistant_content},
    ]
    metadata = dict(row.get("metadata") or {})
    metadata.update(
        {
            "source": source_tag,
            "ablation_no_intent": True,
            "ablation_no_answer_template": True,
            "model_input_fields": "user_query,external_info",
            "intent_hidden_from_input": True,
            "answer_template_hidden_from_input": True,
            "original_intent": row.get("intent"),
            "has_external_info": bool(external_info.strip()),
            "synthesized_by_api": source_tag == "executor_no_intent_api",
            "include_reasoning": include_reasoning,
        }
    )
    return {
        "id": f"{row.get('id')}_no_intent",
        "source_id": row.get("source_id") or row.get("id"),
        "user_query": user_query,
        # Keep these only as metadata/top-level labels for analysis; they are not
        # used in messages and therefore not provided to the model.
        "intent": row.get("intent"),
        "answer_template": None,
        "external_info": external_info,
        "file_write_plan": row.get("file_write_plan"),
        "file_write_result": row.get("file_write_result"),
        "messages": messages,
        "executor_raw_output": {
            "reasoning_content": reasoning,
            "content": answer,
            "text": assistant_content,
        },
        "metadata": metadata,
    }


def convert_row_copy(row: dict[str, Any], include_reasoning: bool = False) -> dict[str, Any] | None:
    raw = row.get("executor_raw_output") or {}
    answer = raw.get("content") if isinstance(raw, dict) else None
    if not isinstance(answer, str) or not answer.strip():
        return None
    reasoning = raw.get("reasoning_content") if isinstance(raw, dict) else None
    return build_output_row(
        row,
        answer=answer,
        reasoning=reasoning if isinstance(reasoning, str) else None,
        include_reasoning=include_reasoning,
        source_tag="executor_no_intent_copy",
    )


def convert_row_api(row: dict[str, Any], parsed: dict[str, Any], include_reasoning: bool = False) -> dict[str, Any] | None:
    return build_output_row(
        row,
        answer=str(parsed.get("answer") or ""),
        reasoning=str(parsed.get("reasoning") or ""),
        include_reasoning=include_reasoning,
        source_tag="executor_no_intent_api",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build no-intent/no-template executor SFT rows.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--synthesis-mode", choices=["api", "copy"], default="api", help="默认 api：用 teacher API 重新合成；copy：复制旧答案仅用于调试。")
    parser.add_argument("--model-name", default=None, help="覆盖 DistillConfig.model_name。")
    parser.add_argument("--max-workers", type=int, default=100, help="API 并发数；默认 DistillConfig.max_workers。")
    parser.add_argument("--max-attempts", type=int, default=DEFAULT_MAX_ATTEMPTS, help="单条样本 teacher 调用+校验最多尝试次数。")
    parser.add_argument("--force-rebuild", action="store_true", help="清空输出文件后重建。默认按 id 断点续跑。")
    parser.add_argument("--max-samples", type=int, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--shuffle", action="store_true")
    parser.add_argument("--require-external-info", action="store_true", help="只保留有外部参考信息的样本。")
    parser.add_argument(
        "--no-reasoning",
        action="store_true",
        help="不把 teacher 的思维链写入 assistant target。默认保留 <think> 思维链。",
    )
    parser.add_argument("--print-one", action="store_true", help="写入后打印第一条样本检查格式。")
    return parser.parse_args()


async def run_api_mode(args: argparse.Namespace, rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cfg = DistillConfig()
    model_name = args.model_name or cfg.model_name or resolve_distill_model()
    max_workers = args.max_workers or cfg.max_workers
    http_timeout = float(os.getenv("AGENT_DISTILL_HTTP_TIMEOUT", "120"))
    client = AsyncOpenAI(
        api_key=cfg.api_key,
        base_url=cfg.base_url or resolve_base_url(),
        timeout=http_timeout,
        max_retries=0,
    )
    sem = asyncio.Semaphore(max_workers)
    file_lock = asyncio.Lock()
    seen = existing_ids(args.output)
    generated: list[dict[str, Any]] = []
    fail_counts: dict[str, int] = {}

    async def gen_one(row: dict[str, Any]) -> None:
        row_id = f"{row.get('id')}_no_intent"
        if row_id in seen:
            return
        user_query = str(row.get("user_query") or "").strip()
        external_info = str(row.get("external_info") or "")
        if not user_query:
            fail_counts["empty_user_query"] = fail_counts.get("empty_user_query", 0) + 1
            return
        async with sem:
            for _ in range(args.max_attempts):
                parsed = await call_teacher(client, model_name, user_query, external_info, cfg.max_retries)
                ok, reason = validate_synthesized(parsed)
                if not ok:
                    fail_counts[reason or "unknown"] = fail_counts.get(reason or "unknown", 0) + 1
                    continue
                converted = convert_row_api(row, parsed, include_reasoning=not args.no_reasoning)
                if not converted:
                    fail_counts["convert_failed"] = fail_counts.get("convert_failed", 0) + 1
                    continue
                async with file_lock:
                    append_jsonl(args.output, converted)
                    seen.add(converted["id"])
                    generated.append(converted)
                return
            fail_counts["max_attempts_exceeded"] = fail_counts.get("max_attempts_exceeded", 0) + 1

    print(f"API 合成 no-intent executor：target={len(rows)} model={model_name} workers={max_workers}")
    for fut in tqdm(asyncio.as_completed([gen_one(row) for row in rows]), total=len(rows), desc="合成 no-intent executor"):
        await fut
    if fail_counts:
        print(f"⚠️ 失败/校验计数：{fail_counts}")
    return generated


async def run_async() -> None:
    args = parse_args()
    rows = load_jsonl(args.input)
    if args.require_external_info:
        rows = [row for row in rows if str(row.get("external_info") or "").strip()]
    if args.shuffle:
        rng = random.Random(args.seed)
        rng.shuffle(rows)
    if args.max_samples is not None:
        rows = rows[: args.max_samples]

    if args.force_rebuild and args.output.exists():
        args.output.write_text("", encoding="utf-8")

    if args.synthesis_mode == "copy":
        output_rows: list[dict[str, Any]] = []
        skipped = 0
        for row in rows:
            converted = convert_row_copy(row, include_reasoning=not args.no_reasoning)
            if converted is None:
                skipped += 1
                continue
            output_rows.append(converted)
        write_jsonl(args.output, output_rows)
        print(f"✅ no-intent executor copy rows: {len(output_rows)} -> {args.output}；skipped={skipped}")
        if args.print_one and output_rows:
            print(json.dumps(output_rows[0], ensure_ascii=False, indent=2)[:6000])
        return

    generated = await run_api_mode(args, rows)
    print(f"✅ no-intent executor API rows: 新增 {len(generated)} -> {args.output}")
    if args.print_one:
        sample = generated[0] if generated else (load_jsonl(args.output)[:1] or [None])[0]
        if sample:
            print(json.dumps(sample, ensure_ascii=False, indent=2)[:6000])


def main() -> None:
    asyncio.run(run_async())


if __name__ == "__main__":
    main()
