"""Synthesize identity SFT samples with the teacher LLM.

This script lives under ``agent/`` only because it imports config + tokenizer +
default health-domain prompts. It does **not** plug into the agent module pipeline; you run it
manually and it appends rows directly to the merged final-prompt JSONL.

Two stages are produced (configurable):

- **planner stage** (system = ``SFT_PLANNER_SYSTEM_PROMPT``):
  assistant outputs a strict JSON ``planning_finish`` with ``intent="其他"``.
  Only the ``<think>`` reasoning is generated by the LLM; the JSON action body
  is built deterministically so the model always learns "skip tools, finish
  planning when asked who/what I am".

- **executor stage** (system = ``EXECUTOR_SYSTEM_PROMPT``):
  the LLM generates BOTH the user question variant and the assistant answer
  (with ``<think>`` reasoning). Each call returns a JSON object so we can
  validate it before writing.

Both stages reuse ``agent.config.DistillConfig`` for the API key / base URL /
model / concurrency settings.

Examples::

    python -m agent.inject_identity --executor-total 200 --planner-total 200
    python -m agent.inject_identity --executor-total 100 --stage executor
    python -m agent.inject_identity --dry-run
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from openai import AsyncOpenAI
from tqdm import tqdm
from transformers import AutoTokenizer

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    from .config import DEDUP_FINAL_PROMPT_FILE, QWEN_BASE_MODEL_PATH, DistillConfig, output_file_for_domain, resolve_base_url, resolve_distill_model
    from .domains.health.executor_prompts import EXECUTOR_SYSTEM_PROMPT
    from .domains.health.prompts import SFT_PLANNER_SYSTEM_PROMPT, TOOL_CATALOG
    from .generator import get_tool_name
except ImportError:  # Allows: python agent/inject_identity.py
    from agent.config import DEDUP_FINAL_PROMPT_FILE, QWEN_BASE_MODEL_PATH, DistillConfig, output_file_for_domain, resolve_base_url, resolve_distill_model
    from agent.domains.health.executor_prompts import EXECUTOR_SYSTEM_PROMPT
    from agent.domains.health.prompts import SFT_PLANNER_SYSTEM_PROMPT, TOOL_CATALOG
    from agent.generator import get_tool_name


DEFAULT_NAME = "司宁健康管理助手"
DEFAULT_TEAM = "南京邮电大学管理学院"
DEFAULT_PRODUCT = "司宁健康管理 agent"
DEFAULT_EXECUTOR_TOTAL = 240
DEFAULT_PLANNER_TOTAL = 240
DEFAULT_MAX_ATTEMPTS = 3
DEFAULT_SEED = 42

QUESTION_BUCKETS_ZH = [
    "你是谁",
    "你叫什么名字",
    "你是哪个团队/公司开发的",
    "你的开发者是谁",
    "请介绍一下你自己",
    "你是 ChatGPT 吗",
    "你是 Qwen 吗",
    "你是 DeepSeek 吗",
    "你能做什么",
    "你的定位是什么",
    "你是基于什么模型训练的",
    "你属于哪家公司的产品",
    "在使用你之前，我想先确认一下你的身份",
    "你跟其他健康管理助手有什么不同",
    "我用你之前需要注意什么",
    "你能替代医生吗",
    "你给的建议靠谱吗",
]

QUESTION_BUCKETS_EN = [
    "Who are you",
    "What's your name",
    "Who developed you",
    "Are you ChatGPT or Qwen",
    "What can you do",
    "Please introduce yourself",
]

PLANNER_FIXED_FINISH_REASON_NO_TOOLS = "用户问题为自我介绍/身份澄清/能力咨询类，不属于健康管理意图，当前也未提供工具，直接结束规划由下游回答。"
PLANNER_FIXED_FINISH_REASON_WITH_TOOLS = "用户问题为自我介绍/身份澄清/能力咨询类，不属于健康管理意图，所列工具与该问题无关，无需调用，直接结束规划由下游回答。"

# planner 身份样本的工具暴露分布：no_tools 仅占一小部分，主流是随机子集 (对身份问题而言全是 irrelevant)
PLANNER_TOOL_MODE_RATIO = [("no_tools", 0.25), ("random_subset", 0.75)]
PLANNER_TOOL_SUBSET_MIN = 2
PLANNER_TOOL_SUBSET_MAX = 6


# ---------------------------------------------------------------------------
# LLM teacher prompts
# ---------------------------------------------------------------------------

EXECUTOR_TEACHER_SYSTEM_PROMPT_TEMPLATE = """你是{name}（由{team}开发的{product}）训练数据合成专家。请合成一条自然、口语化的"身份相关"样本，用于让模型学会回答用户关于自身的提问。

【固定身份信息（必须严格遵守）】
- 名字：{name}
- 开发团队：{team}
- 产品定位：{product}，专注健康管理（饮食调理 / 运动养生 / 体质辨识 / 症状调理 / 情志调节 五个方向）

【回答应该覆盖的要点（不必全部出现，但每条至少覆盖 2-3 个，避免回答过短）】
1. 自我介绍（名字、团队）
2. 能做什么（5 大方向）
3. 使用注意事项：不替代医生 / 不做诊断或处方 / 涉及病症与用药请就医 / 描述越具体建议越贴合
4. 风格定位：温和、谨慎、可执行
5. 如果用户在猜其他模型：先明确否认，再说自身定位

【输出严格为一个 JSON 对象（不带 markdown 围栏，不带任何解释文字）】
{{
  "user_query": "<符合提示主题的用户提问，自然口语化，可以是简短的也可以详细一些，10-60字。中英文按提示主题决定>",
  "reasoning": "<assistant 的内部思考，30-100字，说明这是身份/能力类问题、要覆盖哪几个要点、要不要提醒就医>",
  "answer": "<最终面向用户的回答，120-400字，自然不死板，可用 Markdown 列表/小标题让结构清晰；必须自报「{name}」由「{team}」开发；必须包含使用注意事项；不要透露底层具体模型型号；不要复读相同模板>"
}}

约束：
- 同一批合成中，请尽量让 user_query 与 answer 的措辞每次都不同
- 不允许出现固定模板字句堆砌
- 不要给具体的医疗诊断或用药建议
- answer 不要使用「作为 AI 模型」这种泛化自指，要落到「{name}」这一身份上
- 输出严格一个 JSON 对象，不输出任何其他字符
"""

PLANNER_TEACHER_SYSTEM_PROMPT_TEMPLATE = """你是健康管理 agent 的训练数据合成专家。当前任务是构造规划阶段对「身份 / 自我介绍 / 能力咨询」类用户问题的处理样本。这类问题不属于五大健康意图，必须直接 planning_finish。

【固定上下文】
- 模型自身：「{name}」，由「{team}」开发的「{product}」
- 五大健康意图：食疗咨询 / 运动指导 / 体质辨识 / 症状调理 / 情志调节
- 当前用户问题归类："其他"
- planner 不应调用任何工具
- 工具暴露场景（{tool_scenario}）：{tool_scenario_desc}

【输出严格为一个 JSON 对象（不带 markdown 围栏，不带任何解释文字）】
{{
  "user_query": "<符合提示主题的用户提问，自然口语化，10-60字>",
  "reasoning": "<planner 的内部思考，40-140字。要点：判断这是身份/能力咨询类问题、不属于五大健康意图、归到"其他"、{tool_reasoning_hint}、信息已足够直接结束规划由下游执行阶段回答>"
}}

约束：
- user_query 不要重复同样措辞，每次造一个新的变体
- reasoning 必须明确写出 intent 归为「其他」、不调用工具、planning_finish 的判断逻辑
- reasoning 不要包含最终用户回复正文（那是下游执行阶段的事）
- 输出严格一个 JSON 对象，不输出任何其他字符
"""

PLANNER_TOOL_SCENARIO_DESC = {
    "no_tools": "当前对话未提供任何可调用工具",
    "random_subset": "当前对话提供了一些健康/检索类工具，但与「身份/能力咨询」这一问题完全无关",
}
PLANNER_TOOL_REASONING_HINT = {
    "no_tools": "明确「未提供工具，无需调用」",
    "random_subset": "明确「虽然提供了若干工具，但都与身份/能力咨询无关，因此不调用」",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def parse_json(text: str) -> dict[str, Any] | None:
    if not text:
        return None
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.S)
    if fenced:
        try:
            return json.loads(fenced.group(1))
        except json.JSONDecodeError:
            pass
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            return None
    return None


def validate_executor_sample(parsed: Any, name: str, team: str) -> tuple[bool, str]:
    if not isinstance(parsed, dict):
        return False, "not_dict"
    user_query = str(parsed.get("user_query") or "").strip()
    answer = str(parsed.get("answer") or "").strip()
    reasoning = str(parsed.get("reasoning") or "").strip()
    if not user_query or not answer or not reasoning:
        return False, "empty_field"
    if len(user_query) < 4 or len(user_query) > 200:
        return False, f"user_query_length={len(user_query)}"
    if len(answer) < 100 or len(answer) > 1200:
        return False, f"answer_length={len(answer)}"
    if name not in answer and name.replace(" ", "") not in answer:
        return False, "missing_name"
    if team not in answer and team.replace(" ", "") not in answer:
        return False, "missing_team"
    forbidden = (
        "作为 AI 模型",
        "作为AI模型",
        "I am ChatGPT",
        "I am Qwen",
        "我是 ChatGPT",
        "我是Qwen",
        "我是 Qwen",
    )
    if any(token in answer for token in forbidden):
        return False, "forbidden_phrase"
    return True, ""


def validate_planner_sample(parsed: Any) -> tuple[bool, str]:
    if not isinstance(parsed, dict):
        return False, "not_dict"
    user_query = str(parsed.get("user_query") or "").strip()
    reasoning = str(parsed.get("reasoning") or "").strip()
    if not user_query or not reasoning:
        return False, "empty_field"
    if len(user_query) < 4 or len(user_query) > 200:
        return False, f"user_query_length={len(user_query)}"
    if len(reasoning) < 30 or len(reasoning) > 400:
        return False, f"reasoning_length={len(reasoning)}"
    if "planning_finish" not in reasoning and "结束规划" not in reasoning:
        return False, "reasoning_missing_finish_signal"
    return True, ""


def existing_ids(path: Path) -> set[str]:
    ids: set[str] = set()
    if not path.exists():
        return ids
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            row_id = row.get("id")
            if row_id:
                ids.add(str(row_id))
    return ids


# ---------------------------------------------------------------------------
# Teacher calls
# ---------------------------------------------------------------------------


async def call_teacher_executor(
    client: AsyncOpenAI,
    model_name: str,
    name: str,
    team: str,
    product: str,
    bucket_hint: str,
    max_retries: int,
) -> dict[str, Any] | None:
    system_prompt = EXECUTOR_TEACHER_SYSTEM_PROMPT_TEMPLATE.format(name=name, team=team, product=product)
    user_prompt = f"请围绕用户主题「{bucket_hint}」合成一条样本。"
    for attempt in range(max_retries):
        try:
            completion = await client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.95,
                top_p=0.95,
            )
            return parse_json(completion.choices[0].message.content or "")
        except Exception as exc:
            if attempt < max_retries - 1:
                await asyncio.sleep(min(2**attempt, 30) + 1)
            else:
                print(f"\n[失败] executor 身份样本达到最大重试次数：{exc}")
                return None
    return None


async def call_teacher_planner(
    client: AsyncOpenAI,
    model_name: str,
    name: str,
    team: str,
    product: str,
    bucket_hint: str,
    max_retries: int,
    tool_scenario: str = "no_tools",
) -> dict[str, Any] | None:
    system_prompt = PLANNER_TEACHER_SYSTEM_PROMPT_TEMPLATE.format(
        name=name,
        team=team,
        product=product,
        tool_scenario=tool_scenario,
        tool_scenario_desc=PLANNER_TOOL_SCENARIO_DESC.get(tool_scenario, PLANNER_TOOL_SCENARIO_DESC["no_tools"]),
        tool_reasoning_hint=PLANNER_TOOL_REASONING_HINT.get(tool_scenario, PLANNER_TOOL_REASONING_HINT["no_tools"]),
    )
    user_prompt = f"请围绕用户主题「{bucket_hint}」合成一条规划阶段样本。"
    for attempt in range(max_retries):
        try:
            completion = await client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.9,
                top_p=0.95,
            )
            return parse_json(completion.choices[0].message.content or "")
        except Exception as exc:
            if attempt < max_retries - 1:
                await asyncio.sleep(min(2**attempt, 30) + 1)
            else:
                print(f"\n[失败] planner 身份样本达到最大重试次数：{exc}")
                return None
    return None


# ---------------------------------------------------------------------------
# Row builders
# ---------------------------------------------------------------------------


def render_executor_prompt(tokenizer, parsed: dict[str, Any]) -> str:
    assistant_content = f"<think>\n{parsed['reasoning'].strip()}\n</think>\n{parsed['answer'].strip()}"
    messages = [
        {"role": "system", "content": EXECUTOR_SYSTEM_PROMPT},
        {"role": "user", "content": parsed["user_query"].strip()},
        {"role": "assistant", "content": assistant_content},
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)


def sample_planner_tools(rng: random.Random) -> tuple[str, list[dict[str, Any]]]:
    """为 planner 身份样本采样工具暴露方式。

    返回 (mode, tools)。mode 为 ``no_tools`` 表示工具列表为空；``random_subset``
    表示从全量工具目录中随机抽取若干个（对身份问题来说全部 irrelevant，模型仍
    应直接 planning_finish）。
    """

    modes, weights = zip(*PLANNER_TOOL_MODE_RATIO)
    mode = rng.choices(modes, weights=weights, k=1)[0]
    if mode == "no_tools" or not TOOL_CATALOG:
        return "no_tools", []
    pool = list(TOOL_CATALOG)
    rng.shuffle(pool)
    upper = min(PLANNER_TOOL_SUBSET_MAX, len(pool))
    lower = min(PLANNER_TOOL_SUBSET_MIN, upper)
    count = rng.randint(lower, upper) if upper >= lower else upper
    return "random_subset", pool[:count]


def render_planner_prompt(
    tokenizer,
    parsed: dict[str, Any],
    tools: list[dict[str, Any]],
) -> str:
    finish_reason = (
        PLANNER_FIXED_FINISH_REASON_NO_TOOLS if not tools else PLANNER_FIXED_FINISH_REASON_WITH_TOOLS
    )
    action_payload = {
        "intent": "其他",
        "action": "planning_finish",
        "finish_reason": finish_reason,
    }
    assistant_content = (
        f"<think>\n{parsed['reasoning'].strip()}\n</think>\n"
        + json.dumps(action_payload, ensure_ascii=False)
    )
    messages = [
        {"role": "system", "content": SFT_PLANNER_SYSTEM_PROMPT},
        {"role": "user", "content": parsed["user_query"].strip()},
        {"role": "assistant", "content": assistant_content},
    ]
    return tokenizer.apply_chat_template(messages, tools=tools, tokenize=False, add_generation_prompt=False)


def make_metadata(
    source_tag: str,
    planner: bool,
    tool_sampling_mode: str = "",
    tool_names: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "merge_source": "identity",
        "source": source_tag,
        "source_id": "",
        "step": 0,
        "action": "planning_finish",
        "include_reasoning": True,
        "planner_overridden": False,
        "tool_names": ",".join(tool_names or []),
        "has_tool_error": False,
        "has_file_write_plan": False,
        "file_written": False,
        "include_tool_errors": False,
        "answer_template_intent": "其他",
        "max_external_chars": 0,
        "planner_tool_sampling_mode": tool_sampling_mode if planner else "",
        "intent": "其他",
        "has_clarification_ask": False,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LLM-synthesized identity SFT data appended to merged final prompt JSONL.")
    parser.add_argument("--name", default=DEFAULT_NAME, help="模型自报的名字。")
    parser.add_argument("--team", default=DEFAULT_TEAM, help="开发团队/公司名。")
    parser.add_argument("--product", default=DEFAULT_PRODUCT, help="产品定位描述。")
    parser.add_argument("--executor-total", type=int, default=DEFAULT_EXECUTOR_TOTAL, help="执行阶段身份样本目标条数。")
    parser.add_argument("--planner-total", type=int, default=DEFAULT_PLANNER_TOTAL, help="规划阶段身份样本目标条数。")
    parser.add_argument("--output", type=Path, default=output_file_for_domain("identity_sft"), help="目标 JSONL 文件，默认写入当前领域输出目录。")
    parser.add_argument("--model-path", type=Path, default=QWEN_BASE_MODEL_PATH, help="用于 apply_chat_template 的 tokenizer 路径。")
    parser.add_argument("--model-name", type=str, default=None, help="覆盖 DistillConfig 的 teacher 模型。")
    parser.add_argument("--max-workers", type=int, default=None, help="并发上限；默认读 DistillConfig.max_workers。")
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=DEFAULT_MAX_ATTEMPTS,
        help="单条样本最多尝试 teacher 调用 + 校验的次数。",
    )
    parser.add_argument(
        "--stage",
        choices=["executor", "planner", "both"],
        default="both",
        help="生成哪一阶段的身份样本（默认 both）。",
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="主题轮换随机种子。")
    parser.add_argument("--dry-run", action="store_true", help="只打印一条 LLM 合成示例，不写入文件。")
    return parser.parse_args()


async def run_async() -> None:
    args = parse_args()
    cfg = DistillConfig()
    rng = random.Random(args.seed)

    stages: list[str]
    if args.stage == "both":
        stages = ["planner", "executor"]
    else:
        stages = [args.stage]

    tokenizer = AutoTokenizer.from_pretrained(str(args.model_path), trust_remote_code=True)
    model_name = args.model_name or cfg.model_name or resolve_distill_model()
    max_workers = args.max_workers or cfg.max_workers
    http_timeout = float(os.getenv("AGENT_DISTILL_HTTP_TIMEOUT", "120"))

    client = AsyncOpenAI(
        api_key=cfg.api_key,
        base_url=cfg.base_url or resolve_base_url(),
        timeout=http_timeout,
        max_retries=0,
    )

    if args.dry_run:
        print("--- dry-run：分别合成一条 planner / executor 示例 ---")
        if "planner" in stages:
            tool_mode_dry, tools_dry = sample_planner_tools(rng)
            parsed = await call_teacher_planner(
                client, model_name, args.name, args.team, args.product,
                rng.choice(QUESTION_BUCKETS_ZH), cfg.max_retries, tool_scenario=tool_mode_dry,
            )
            print("\n[planner sample]\n", json.dumps(parsed, ensure_ascii=False, indent=2))
            if parsed:
                print(f"\n[planner tool mode={tool_mode_dry}, tool_count={len(tools_dry)}]")
                print("\n[planner rendered prompt]\n")
                print(render_planner_prompt(tokenizer, parsed, tools_dry))
        if "executor" in stages:
            parsed = await call_teacher_executor(
                client, model_name, args.name, args.team, args.product, rng.choice(QUESTION_BUCKETS_ZH), cfg.max_retries
            )
            print("\n[executor sample]\n", json.dumps(parsed, ensure_ascii=False, indent=2))
            if parsed:
                print("\n[executor rendered prompt]\n")
                print(render_executor_prompt(tokenizer, parsed))
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    seen = existing_ids(args.output)
    sem = asyncio.Semaphore(max_workers)
    file_lock = asyncio.Lock()
    success_counter: Counter[str] = Counter()
    fail_counter: Counter[str] = Counter()

    def pick_bucket() -> str:
        # 80% 中文主题、20% 英文主题，混合驱动多样性
        pool = QUESTION_BUCKETS_ZH if rng.random() > 0.2 else QUESTION_BUCKETS_EN
        return rng.choice(pool)

    async def gen_executor(idx: int) -> bool:
        row_id = f"identity_executor_llm_{idx:05d}"
        if row_id in seen:
            return True
        async with sem:
            for _ in range(args.max_attempts):
                bucket_hint = pick_bucket()
                parsed = await call_teacher_executor(
                    client, model_name, args.name, args.team, args.product, bucket_hint, cfg.max_retries
                )
                ok, reason = validate_executor_sample(parsed, args.name, args.team)
                if not ok:
                    fail_counter[reason or "unknown"] += 1
                    continue
                prompt = render_executor_prompt(tokenizer, parsed)
                row = {
                    "id": row_id,
                    "prompt": prompt,
                    "metadata": make_metadata("identity_executor_llm", planner=False),
                }
                async with file_lock:
                    with args.output.open("a", encoding="utf-8") as f:
                        f.write(json.dumps(row, ensure_ascii=False) + "\n")
                success_counter["executor"] += 1
                return True
            return False

    async def gen_planner(idx: int) -> bool:
        row_id = f"identity_planner_llm_{idx:05d}"
        if row_id in seen:
            return True
        async with sem:
            for _ in range(args.max_attempts):
                bucket_hint = pick_bucket()
                tool_mode, tools = sample_planner_tools(rng)
                parsed = await call_teacher_planner(
                    client, model_name, args.name, args.team, args.product, bucket_hint,
                    cfg.max_retries, tool_scenario=tool_mode,
                )
                ok, reason = validate_planner_sample(parsed)
                if not ok:
                    fail_counter[reason or "unknown"] += 1
                    continue
                prompt = render_planner_prompt(tokenizer, parsed, tools)
                tool_names = [name for name in (get_tool_name(t) for t in tools) if name]
                row = {
                    "id": row_id,
                    "prompt": prompt,
                    "metadata": make_metadata(
                        "identity_planner_llm",
                        planner=True,
                        tool_sampling_mode=tool_mode,
                        tool_names=tool_names,
                    ),
                }
                async with file_lock:
                    with args.output.open("a", encoding="utf-8") as f:
                        f.write(json.dumps(row, ensure_ascii=False) + "\n")
                success_counter["planner"] += 1
                return True
            return False

    coros: list[Any] = []
    if "planner" in stages:
        coros.extend(gen_planner(idx) for idx in range(args.planner_total))
    if "executor" in stages:
        coros.extend(gen_executor(idx) for idx in range(args.executor_total))
    print(
        f"目标合成：planner={args.planner_total if 'planner' in stages else 0}，"
        f"executor={args.executor_total if 'executor' in stages else 0}；"
        f"模型={model_name}，并发={max_workers}。"
    )

    for fut in tqdm(asyncio.as_completed(coros), total=len(coros), desc="合成身份样本"):
        await fut

    print(
        f"\n✅ 身份 SFT 样本写入 {args.output}\n"
        f"  planner 成功：{success_counter['planner']}；executor 成功：{success_counter['executor']}\n"
        f"  失败原因计数：{dict(fail_counter) if fail_counter else '(无)'}"
    )


def main() -> None:
    asyncio.run(run_async())


if __name__ == "__main__":
    main()
